### ISSUE TITLE
error

### ISSUE THREAD

**Issue by pharaoh347** [Freddywhest/DotcoinBot#7]
[2024-09-12 04:44:07] | ERROR | Unhandled error while receiving data
TypeNotFoundError: Could not find a matching Constructor ID for the TLObject that was supposed to be
        read with ID 1294139288. Most likely, a TLObject was trying to be read when
         it should not be read. Remaining bytes: 508
    at BinaryReader.tgReadObject (/home/user1/DotcoinBot/node_modules/telegram/extensions/BinaryReader.js:195:31)
    at VirtualClass.readResult (/home/user1/DotcoinBot/node_modules/telegram/tl/api.js:451:35)
    at MTProtoSender._handleRPCResult (/home/user1/DotcoinBot/node_modules/telegram/network/MTProtoSender.js:554:44)
    at MTProtoSender._processMessage (/home/user1/DotcoinBot/node_modules/telegram/network/MTProtoSender.js:476:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async MTProtoSender._recvLoop (/home/user1/DotcoinBot/node_modules/telegram/network/MTProtoSender.js:424:17) {
  invalidConstructorId: 1294139288,
  remaining: <Buffer 98 ff 22 4d 01 00 00 00 07 58 68 f7 4d af b5 3c fe e6 01 00 68 74 74 70 73 3a 2f 2f 64 6f 74 2e 64 61 70 70 6c 61 62 2e 78 79 7a 2f 23 74 67 57 65 62 ... 458 more bytes>
}
[2024-09-12 04:44:07] | ERROR | [dotcoin] |  | ❗️Unknown error during Authorization: Error: Could not find a matching Constructor ID for the TLObject that was supposed to be

**Comment by lucasnguyen3979** [comment]
I have the same error.

**Comment by Freddywhest** [comment]
Fixed
